### ISSUE TITLE
Scope of this library?

### ISSUE THREAD

**Issue by NNEU-1** [katoemba/SwiftUPnP#2]
Hi,

I am a bit confused on the scope of this library. It's called "SwiftUPnP", but it seems that the focus is on OpenHome devices + UPnP servers.

It seems that the conventional UPnP MediaRenderer device is not supported. 

Is that intentionally the scope of this library or WIP?

**Comment by katoemba** [comment]
The focus of the library is on control points, to interact with media servers and media renderers. Included are the standard UPnP services and OpenHome services (based on Davaar, not Eriskay). It's been tested with BubbleUPnP and upmpdcli and AssetUPnP.

Discovery will filter the types specified when initializing UPnPRegistry.

Additional service implementations for which a scdp file is available can be generated through the command line code generator.
