### ISSUE TITLE
Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by NNEU-1** [katoemba/SwiftUPnP#3]
Hi,

i tested this library with the official OpenHome demo player for Mac.

There is a problem with the "typedService()" function, as it doesn't process the "urn:av-openhome-org:service:Config:1" service type.

This results in this item being processed by the "default" of the switch statement, which will fail because this service seemingly doesn't have an eventUrl.

> 
>         default:
>             return UPnPService(device: device,
>                                controlUrl: URL(string: deviceService.controlURL, relativeTo: baseURL)!,
>                                scpdUrl: URL(string: deviceService.SCPDURL, relativeTo: baseURL)!,
>                     --->> eventUrl: URL(string: deviceService.eventSubURL, relativeTo: baseURL)!, <<---
>                                serviceType: deviceService.serviceType,
>                                serviceId: deviceService.serviceId,
>                                eventPublisher: eventPublisher,
>                                eventCallbackUrl: eventCallbackUrl)
>

**Comment by katoemba** [comment]
The eventUrl is made optional, and 5 additional OpenHome services are added.
