### ISSUE TITLE
Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by paulober** [katoemba/SwiftUPnP#4]
SwiftUPnP/UserAgentGenerator.swift:76: Fatal error: Unexpectedly found nil while unwrapping an Optional value

in this line
```swift
let version = dictionary["CFBundleShortVersionString"] as! String
```

**Comment by katoemba** [comment]
Solved with commit bb27d50ea4c2b601816ce393429b06776efb70d0.
