### ISSUE TITLE
doesn't work on iOS

### ISSUE THREAD

**Issue by melchior-voidwolf** [katoemba/SwiftUPnP#6]
Thank you so much for your selfless dedication to this library!

My code works fine in the simulator, but not on the real machine, maybe I need to add permissions to the Plist file.
 
I tried to add the following code
<dict>
    <key>NSLocalNetworkUsageDescription</key
	<string>In order to discover media servers we will need access to your local network. This is also needed to find Chromecast devices.</string>
	<key>com.apple.developer.networking.multicast</key>
	<true/>
</dict

Works fine on Mac, doesn't work on iOS

**Comment by katoemba** [comment]
You need to request permission from Apple to use this entitlement. The exact use in the plist file is this:
	`<key>com.apple.developer.networking.multicast</key>`
	`<true/>`

The page https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_multicast contains a link where you can request this permission for your app.

I will add this to the readme file.
