### ISSUE TITLE
Can not find device

### ISSUE THREAD

**Issue by minhvblc** [katoemba/SwiftUPnP#7]
I just try your example code but no device came up. It come with this error "nw_connection_copy_connected_remote_endpoint_block_invoke [C3] Client called nw_connection_copy_connected_remote_endpoint on unconnected nw_connection". Can you fix this?

**Comment by katoemba** [comment]
By default 3 UPnP device types are detected, if you want to discover others you need to pass them when you create a UPnPRegistry object. The reported errors are not related to discovery, I see them as well when devices are properly discovered.

See the init function in UPnPRegistry:
```
init(types: [String] = ["urn:schemas-upnp-org:device:MediaServer:1", 
                        "urn:linn-co-uk:device:Source:1", 
                        "urn:av-openhome-org:device:Source:1"],
     httpServerPortRange: Range<UInt16> = 51000..<51099)
```

Further troubleshooting you have to do yourself.

**Comment by minhvblc** [comment]
Thank you sir. I'm new with upnp. I want to set RTSP URI with AVTransport, but the response always come with illegal mime type. This is my protocolInfo "rtsp-rtp-udp:*:mpeg4:* and this is RTSP URI that i test rtsp://rtsp-test-server.viomic.com:554/stream. Could you show me how to fix it? @katoemba
