### ISSUE TITLE
Custom UPnPRegistry types usage

### ISSUE THREAD

**Issue by MainSwitch** [katoemba/SwiftUPnP#8]
I need to use custom types for UPnPRegistry such as urn:av-openhome-org:service:Transport:1, but your UPnPRegistry implementation does not allow this. Can you implement setting custom types for the UPnP Registry class or make init public?

**Comment by katoemba** [comment]
The types to discover are now a parameter to UPnPRegistry.startDiscovery, so you can override it.

Note that discovery only works on devices, not individual services. So you need to use type of the device, then the available services will be automatically loaded when a device is discovered.

**Comment by MainSwitch** [comment]
@katoemba 
Thank you !
