### ISSUE TITLE
UPnPRegistry Causing Crashes on closure #3 in UPnPRegistry.add(_:) + 186

### ISSUE THREAD

**Issue by evilutioner** [katoemba/SwiftUPnP#9]
Many users have encountered crashes due to unsafe processing in the UPnPRegistry component of the SwiftUPnP library. After investigating the issue, I identified the root cause and have rewritten the affected code to ensure safe and reliable processing.

I have prepared a fix and would like to contribute it to the library to prevent future occurrences of this problem.

**Comment by katoemba** [comment]
Thanks for the fix, the pull request is merged.

You might want to check the detection logic, because it's strange that some of this data (which I believed to be mandatory) is not available.
